//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostNestQuestClient.HTTP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LostItem", Namespace="http://schemas.datacontract.org/2004/07/LostNestQuestService.Contracts")]
    [System.SerializableAttribute()]
    public partial class LostItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoundItem", Namespace="http://schemas.datacontract.org/2004/07/LostNestQuestService.Contracts")]
    [System.SerializableAttribute()]
    public partial class FoundItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HTTP.ILostNestQuestService")]
    public interface ILostNestQuestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILostNestQuestService/ReportLostItem", ReplyAction="http://tempuri.org/ILostNestQuestService/ReportLostItemResponse")]
        string ReportLostItem(LostNestQuestClient.HTTP.LostItem lostItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILostNestQuestService/ReportLostItem", ReplyAction="http://tempuri.org/ILostNestQuestService/ReportLostItemResponse")]
        System.Threading.Tasks.Task<string> ReportLostItemAsync(LostNestQuestClient.HTTP.LostItem lostItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILostNestQuestService/ReportFoundItem", ReplyAction="http://tempuri.org/ILostNestQuestService/ReportFoundItemResponse")]
        string ReportFoundItem(LostNestQuestClient.HTTP.FoundItem foundItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILostNestQuestService/ReportFoundItem", ReplyAction="http://tempuri.org/ILostNestQuestService/ReportFoundItemResponse")]
        System.Threading.Tasks.Task<string> ReportFoundItemAsync(LostNestQuestClient.HTTP.FoundItem foundItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILostNestQuestService/GetAllLostItems", ReplyAction="http://tempuri.org/ILostNestQuestService/GetAllLostItemsResponse")]
        LostNestQuestClient.HTTP.LostItem[] GetAllLostItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILostNestQuestService/GetAllLostItems", ReplyAction="http://tempuri.org/ILostNestQuestService/GetAllLostItemsResponse")]
        System.Threading.Tasks.Task<LostNestQuestClient.HTTP.LostItem[]> GetAllLostItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILostNestQuestService/GetAllFoundItems", ReplyAction="http://tempuri.org/ILostNestQuestService/GetAllFoundItemsResponse")]
        LostNestQuestClient.HTTP.FoundItem[] GetAllFoundItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILostNestQuestService/GetAllFoundItems", ReplyAction="http://tempuri.org/ILostNestQuestService/GetAllFoundItemsResponse")]
        System.Threading.Tasks.Task<LostNestQuestClient.HTTP.FoundItem[]> GetAllFoundItemsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILostNestQuestServiceChannel : LostNestQuestClient.HTTP.ILostNestQuestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LostNestQuestServiceClient : System.ServiceModel.ClientBase<LostNestQuestClient.HTTP.ILostNestQuestService>, LostNestQuestClient.HTTP.ILostNestQuestService {
        
        public LostNestQuestServiceClient() {
        }
        
        public LostNestQuestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LostNestQuestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LostNestQuestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LostNestQuestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ReportLostItem(LostNestQuestClient.HTTP.LostItem lostItem) {
            return base.Channel.ReportLostItem(lostItem);
        }
        
        public System.Threading.Tasks.Task<string> ReportLostItemAsync(LostNestQuestClient.HTTP.LostItem lostItem) {
            return base.Channel.ReportLostItemAsync(lostItem);
        }
        
        public string ReportFoundItem(LostNestQuestClient.HTTP.FoundItem foundItem) {
            return base.Channel.ReportFoundItem(foundItem);
        }
        
        public System.Threading.Tasks.Task<string> ReportFoundItemAsync(LostNestQuestClient.HTTP.FoundItem foundItem) {
            return base.Channel.ReportFoundItemAsync(foundItem);
        }
        
        public LostNestQuestClient.HTTP.LostItem[] GetAllLostItems() {
            return base.Channel.GetAllLostItems();
        }
        
        public System.Threading.Tasks.Task<LostNestQuestClient.HTTP.LostItem[]> GetAllLostItemsAsync() {
            return base.Channel.GetAllLostItemsAsync();
        }
        
        public LostNestQuestClient.HTTP.FoundItem[] GetAllFoundItems() {
            return base.Channel.GetAllFoundItems();
        }
        
        public System.Threading.Tasks.Task<LostNestQuestClient.HTTP.FoundItem[]> GetAllFoundItemsAsync() {
            return base.Channel.GetAllFoundItemsAsync();
        }
    }
}
